# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 김광현
title: 오늘 모르면 내일은 아는 개발자 김광현입니다
email: kimkh1517@gmail.com
website: https://devkhk.tistory.com

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username: devkhk
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: username
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  오늘 모르는게 생기면 내일은 알고 있는 신입 개발자 김광현입니다. 
  
  Java로 처음 개발공부를 시작했고 안드로이드 프로젝트 경험, 웹 서버 프로젝트 경험으로 Full stack 기본을 이해했습니다. 개발 공부를 하다보니 서버에서 데이터를 다루는 백엔드 개발자가 되고자 했습니다. 이후 백엔드에서도 세부적인 데이터 엔지니어링이란 분야를 알게 되었고, 제가 목표로 하는 백엔드 개발이라는 확신이 들어 전문적인 <mark>데이터 엔지니어</mark>가 되기위해 공부하고 있습니다.

  CS전공자가 아니기 때문에 CS지식을 익히기 위해 네이버 커넥트재단이 제공하는 <mark>CS50</mark>(하버드 대학교의 컴퓨터과학 입문 강좌)로 부족한 CS기초를 공부했습니다. <mark>빅데이터</mark>와 <mark>클라우드</mark>에 대한 이해부터 데이터 수집, 저장, 처리, 분석, 시각화까지 데이터 분석의 전체 과정에 걸친 <mark>데이터 파이프라인</mark> 구축을 공부하고 있습니다.

content:
  - title: Skills # skills section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Backend
        description: | # this will include new lines to allow paragraphs
          - Python, PHP, Java
          - Apache Spark, Apache Airflow, Apache kafka(예정)
          - Laravel, Composer
          - MVP
      - layout: left
        title: Devops
        description: | # this will include new lines to allow paragraphs
          - Linux
          - Nginx, Apache
          - AWS EC2, AWS S3
          - MySQL, MariaDB
          
      - layout: left
        title: Frontend
        description: | # this will include new lines to allow paragraphs
          - Html/CSS
          - JS, Jqeury
          - Json, Ajax

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: (주)델리아이
        link: http://deliiglobal.com
        # link_text: boringcompany.com
        sub_title: 백앤드 개발 외주 프리랜서 계약
        caption: 2021.10 - 2021.11
        quote: > 
          웹 페이지 백앤드 개발을 맡아했습니다. 
        description: | # this will include new lines to allow paragraphs
            퍼블리싱 된 프론트에 기능을 추가하고 서버에서 필요한 데이터를 가져와 뿌려주는 작업을 했습니다. <mark>카카오맵 API</mark>를 사용해 다중오버레이 작업을 했고, 폴더에 저장된 텍스트 파일을 한줄씩 읽어와 데이터를 뿌려주는 기능을 구현했습니다.
            개발자체는 어렵지 않았지만 처음으로 누군가가 요구하는 기능을 만들면서 개발과정에서 <mark>소통</mark>의 중요성을 이해할 수 있었던 시간이었습니다.
            
            <mark>사용 기술 요약</mark>
            - PHP Laravel Framwork
            - KakaoMap API


    # layout: list # Type of content section (list/text)
    # content:
    #   - layout: left
    #     title: The Boring Company
    #     link: boringcompany.com
    #     # link_text: boringcompany.com
    #     sub_title: Senior Network System Administrator
    #     caption: November 2017 - Present
    #     quote: >
    #       Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
    #     description: | # this will include new lines to allow paragraphs
    #         Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.
    
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
    - layout: left
      title: KHK-Market
      sub_title: 메이플 스토리 경매장을 모티브한 게임 아이템 경매장
      link: github.com/devkhk/khk-market
      caption: 2021.04 - 2021.05
      # link_text: Project Website
      additional_links:
        - title: KHK-Market
          # icon: fab fa-github
          # url: github.com/devkhk/khk-market

        # - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #   icon: fab fa-github
        #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
      description: | # this will include new lines to allow paragraphs
        건강상의 문제로 약 1년여만에 개발 공부를 다시 시작하게 된 후 제작한 웹 사이트입니다. 휴식기간 동안 가끔 즐기던 게임인 메이플스토리의 <mark>경매장</mark>을 모티브삼아 웹사이트로 만들어보았습니다.
        개발 목적은 개발에 대한 감각을 되살리고 여러가지 조건에 쿼리문을 다양하게 적용해보고 싶었습니다. 자세한 내용은 깃허브에 정리해두었습니다.

        <mark>사용 기술 요약</mark>
        - bootstrap5
        - PHP PDO
        - DB transaction, DB triger

    - layout: left
      title: My_web
      sub_title: 처음 웹서버를 공부하면서 만든 블로그 웹입니다.
      link: github.com/devkhk/my_web
      caption: 2020.02 - 2021.03
      # link_text: Project Website
      additional_links:
        - title: My_web
          # icon: fab fa-github
          # url: github.com/devkhk/my_web
        # - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #   icon: fab fa-github
        #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)

      description: | # this will include new lines to allow paragraphs
        웹 서버를 처음 구현하면서 백엔드에 대한 이해가 생기는 좋은 시간이었습니다. 직접 APM을 구성하고 리눅스에서 터미널 명령어를 다뤄보면서 내가 개발고수가 된 느낌이 들면서 이때부터 백앤드 개발자가 되어야겠다고 다짐했습니다.
        자세한 내용은 깃허브에 정리해두었습니다.

        <mark>사용 기술 요약</mark>
        - CRUD
        - 세션, 쿠키
        - SMTP 이메일 서비스
        - 댓글 : disqus API
        - 스팸방지 : recaptcha2 API
        - Summernote : ajax 다중이미지 처리
        - 썸네일 : 이미지 압축
    
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 패스트캠프 실시간 빅데이터 처리 Spark & Flink
        caption: 2022.03 - 
        sub_title: 우버 모빌리티 데이터로 실시간 빅데이터 처리 실습
        description: | 
         - 실무 데이터 처리의 End - End 학습
         - 우버 모빌리티 데이터로 실시간 빅데이터 처리 실습
         - 일괄처리 VS 실시간 빅데이터 처리 비교 학습
         - 오케스트레이션으로 데이터 엔지니어링 스케쥴링 학습

      - layout: left
        title: 부스트코스 AI Basic 코칭스터디 1기 리드 부스터 수료
        caption: 2022.01 - 02
        sub_title: 네이버 컨넥트재단에서 운영하는 인공지능 교육 프로그램 중 AI기초
        link: http://www.boostcourse.org/certificate/A20220310-275895?langCode=ko
        link_text: <mark>리더 수료증</mark>
        description: | # this will include new lines to allow paragraphs
          - 인공지능 전반에 필요한 기초 습득
          - 머신러닝을 위한 라이브러리 Numpy, Pandas 등을 이해하고 구현
          - 머신 러닝 알고리즘에 대한 이해
          - 자기 주도적 학습, 팀 학습, 코칭 결합된 스터디
  
      - layout: left
        title: 패스트 캠프 클라우드를 활용한 데이터 파이프라인 구축
        caption: 2021.12 - 2022.01
        sub_title: 데이터 수집, 저장, 처리, 분석, 시각화까지 모든 단계의 파이프라인 구축
        description: | # this will include new lines to allow paragraphs
         - 데이터 파이프라인 전체 과정 커버
         - AWS와 Spark를 포함한 다양한 툴 활용
         - AWS 운영, 코스트 최적화 노하우
         - 실무와 유사한 환경 실습

      - layout: left
        title: 네이버 컨넥트재단 부스트코스 컴퓨터 과학 CS50
        caption: 2021.12
        sub_title: 하버드 대학교의 컴퓨터과학 입문 강좌
        link: http://www.boostcourse.org/certificate/A20211227-906785?langCode=ko
        link_text: <mark>수료증</mark>
        description: | # this will include new lines to allow paragraphs
          - 컴퓨터 과학의 기초 개념 이해
          - C를 이용한 배열, 자료구조, 알고리즘 실습
          - 프로그래밍에 필요한 컴퓨팅 사고 향상
          - [CS강의 블로그 정리](https://devkhk.tistory.com/category/Development/cs)

      - layout: left
        title: 동양 미래 대학교
        caption: 2017 - 2019
        sub_title: 전자정보공학과
        description: | # this will include new lines to allow paragraphs
          - 4.39/4.5 졸업

  # - title: 외부 활동
  #   layout: text
  #   content: | # this will include new lines to allow paragraphs
  #     Alongside my interests in networks and software engineering some of my other interests and hobbies are:
  #     - Rock climbing
  #     - Gaming
  #     - Knitting
  #     - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

  #     Look at this cool image  
  #     ![Trees](images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
